### ISSUE TITLE
About execution flow

### ISSUE THREAD

**Issue by nikhil-patare007** [GottfriedCP/Blockchain-based-E-Voting-Simulation#3]
hello Sir , 
   I am a student learning a blockchain technology .  I want a complte execution flow of the evoting simulation . means which files are executing first and other important aspects of your project . Thank you.

**Comment by GottfriedCP** [comment]
1. Get your virtual environment ready (recommended). Install necessary packages: `pip install -r reqs.txt`.
2. Locate the 'manage.py' file. Run `python manage.py runserver`. Then access http://localhost:8000.
3. From the homepage, either run 'Block' or 'Chain' section.

Note:
The private key used in this demo is located in 'bbevoting_project' folder (`demo_private.pem`), while the corresponding public key is hard coded in settings.py (look for `PUBLIC_KEY`).

**Comment by nikhil-patare007** [comment]
thank you so much
