### ISSUE TITLE
private key not registered

### ISSUE THREAD

**Issue by jayakumarpujar** [GottfriedCP/Blockchain-based-E-Voting-Simulation#4]
the private key which is given in the bbevoting is not registered
![Screenshot from 2019-09-15 09-33-54](https://user-images.githubusercontent.com/46277891/64916514-ff9ea300-d79b-11e9-8f06-8ecba84b06c4.png)

**Comment by GottfriedCP** [comment]
Please provide the steps to reproduce the issue.
Don't forget to check the settings.py for PUBLIC_KEY and make sure to paste
all the contents of demo_private.pem into text box.
