### ISSUE TITLE
Exception Value:	 no such table: simulation_vote

### ISSUE THREAD

**Issue by Krishna812** [GottfriedCP/Blockchain-based-E-Voting-Simulation#9]
While running on server when i try to click on start,see transcation or see block it gives me error no table exist :simulation_vote or simulation_block.  Am i missing any database file?

**Comment by GottfriedCP** [comment]
Try to run below commands:
`python manage.py makemigrations`

and

`python manage.py migrate`

**Comment by Krishna812** [comment]
Thnks a lot :)
